language: android

jdk: oraclejdk7

android:
  components:
    - platform-tools
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew build
